# Generated by Django 5.0.1 on 2024-02-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img_product',
            field=models.ImageField(blank=True, null=True, upload_to='product_photos/'),
        ),
    ]
