# Generated by Django 5.0.2 on 2024-02-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonapp', '0002_product_img_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img_product',
            field=models.ImageField(null=True, upload_to='products/'),
        ),
    ]
